keys:
  - &users:
    - &boticelli age157l8w5myfqxd35svn29ggr7pquqgv4py97ztafu4tf8kcrwa6a3sugnla0
  - &hosts:
    - &thinkpad age1k4rwzrpmnvuz6r36ugzk2tdf50d2nu7afecucn2dp4w8sx03a3dsz0phw4
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *thinkpad
      - *boticelli
