keys:
  - &boticelli 0098D3F49DA1184BAADA5BBB98C7C7A7441867D1
  - &beelink age1ldntuzspe5rv84wlepyqcujqazc6fdz3t7n7ylvx6strg9tveu8qxv4wkl
  - &minisforum age13guvh6sk7sytx65uakhew7pcxq82f78ulemjxykf3rdvchkkxyvq90aylc
  - &huawei age1nr7wuxk6d3em5pdnmredtd0st7sqjs2vmvpayg0em60t63xfudns4ek08k
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *beelink
      - *minisforum
      - *huawei
      pgp:
      - *boticelli
