keys:
  - &users:
    - &boticelli age1jx5eqk3xvsakg32phtl52zgus5pclmmak97fx87xe56jkmm885nqh7gamg
  - &hosts:
    - &vm age1pytyc9za9af6d90fsnm8jneyqq33wkejt5xrqhh099scfd2l6eas8mxqz3
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *vm
      - *boticelli
