# Justfile for nodejs

set shell := ["fish", "-c"]

mongostart:
    mkdir -p ./.database
    touch ./.database/mongo.log
    mongod --dbpath ./.database --logpath ./.database/mongo.log --fork --quiet

mongostop:
    -mongosh --eval "db.getSiblingDB('admin').shutdownServer()"

mongoremove:
    rm -rf ./.database
